<a href="https://colab.research.google.com/github/Mish2j/Gram_Schmidt/blob/main/Gram_Schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

def gram_schmidt(vectors):

  orthonormal_vectors = []

  for current_vector in vectors:
    orthogonal_vector = current_vector.copy()

    for existing_orthonormal_vector in orthonormal_vectors:
      projection_coefficient = np.dot(current_vector, existing_orthonormal_vector)/np.dot(existing_orthonormal_vector, existing_orthonormal_vector)
      projection = projection_coefficient * existing_orthonormal_vector
      orthogonal_vector -= projection

    # Normalize the vector to make it unit length
    normalized_vector = orthogonal_vector / np.linalg.norm(orthogonal_vector)

    orthonormal_vectors.append(normalized_vector)
      # projection = dot(existing,orth)/dot(orth,orth) * orth

  return np.array(orthonormal_vectors)

vector_1 = np.array([2, 1, -1], dtype=float)
vector_2 = np.array([1, 1, 0], dtype=float)
vector_3 = np.array([0, -1, 1], dtype=float)

orthonormal_set = gram_schmidt([vector_1, vector_2, vector_3])

print(orthonormal_set)

# Verify orthogonality
print(np.dot(orthonormal_set[0], orthonormal_set[1]))
print(np.dot(orthonormal_set[0], orthonormal_set[2]))
print(np.dot(orthonormal_set[1], orthonormal_set[2]))

# Verify unit length
print(np.linalg.norm(orthonormal_set[0]))
print(np.linalg.norm(orthonormal_set[1]))
print(np.linalg.norm(orthonormal_set[2]))

[[ 0.81649658  0.40824829 -0.40824829]
 [ 0.          0.70710678  0.70710678]
 [ 0.57735027 -0.57735027  0.57735027]]
0.0
-1.1102230246251565e-16
0.0
1.0
0.9999999999999999
0.9999999999999999
